/**
 * List of DOM pointer, mouse, touch, click, wheel, drag, clipboard, and
 * input events intercepted and suppressed during Cognito Privacy Mode.
 */
export const BLOCKED_POINTER_EVENTS = [
  "pointerdown",
  "pointerup",
  "pointermove",
  "pointerover",
  "pointerout",
  "pointerenter",
  "pointerleave",
  "mousedown",
  "mouseup",
  "mousemove",
  "mouseover",
  "mouseout",
  "mouseenter",
  "mouseleave",
  "touchstart",
  "touchend",
  "touchmove",
  "touchcancel",
  "click",
  "dblclick",
  "auxclick",
  "contextmenu",
  "wheel",
  "dragstart",
  "drag",
  "dragend",
  "dragenter",
  "dragover",
  "dragleave",
  "drop",
  "paste",
  "copy",
  "cut",
  "beforeinput",
  "input",
  "compositionstart",
  "compositionupdate",
  "compositionend",
] as const;
