packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true

patchedDependencies:
  '@radix-ui/react-compose-refs@1.1.2': patches/@radix-ui__react-compose-refs@1.1.2.patch
  '@radix-ui/react-slot@1.2.3': patches/@radix-ui__react-slot@1.2.3.patch
