[package]
name = "dam-hopper-native"
version = "0.1.0"
description = "DamHopper native client"
authors = ["DamHopper contributors"]
edition = "2021"

[lib]
name = "dam_hopper_native_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[workspace]
