use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::agent_status::types::AgentKind;

/// Bundled standalone OMP TypeScript extension source.
pub const OMP_AGENT_STATUS_ASSET: &str = include_str!("assets/omp-agent-status.ts");

/// Bundled native launcher template asset.
pub const NATIVE_LAUNCHER_ASSET: &str = include_str!("assets/native-agent-status.sh");

/// Current managed adapter version.
pub const MANAGED_ADAPTER_VERSION: &str = "1.0.0";

/// Relative subpath within the OMP agent directory.
pub const EXTENSION_SUBPATH: &str = "extensions/dam-hopper-agent-status.ts";

/// Subpath to native launcher script within agent directory.
pub const MANAGED_LAUNCHER_SUBPATH: &str = "hooks/dam-hopper-agent-status";

/// Subpath to native ownership manifest within agent directory.
pub const MANAGED_MANIFEST_SUBPATH: &str = "hooks/dam-hopper-agent-status.manifest.json";

const MANAGED_HEADER_PREFIX: &str = "// @generated by dam-hopper-server integration omp";
const VERSION_PREFIX: &str = "// dam-hopper-managed-version: ";
const HASH_PREFIX: &str = "// dam-hopper-content-sha256: ";

#[derive(Debug, Error)]
pub enum IntegrationError {
    #[error("Agent directory must be an absolute path: '{0}'")]
    NonAbsolutePath(PathBuf),

    #[error("Agent directory does not exist or is not a directory: '{0}'")]
    InvalidAgentDirectory(PathBuf),

    #[error("Refusing to operate on symlink: '{0}'")]
    SymlinkNotAllowed(PathBuf),

    #[error("Target path is not a regular file: '{0}'")]
    NotRegularFile(PathBuf),

    #[error("Refusing to overwrite locally modified or unmanaged file at '{0}'")]
    RefusingOverwriteModified(PathBuf),

    #[error("Refusing to delete locally modified or unmanaged file at '{0}'")]
    RefusingDeleteModified(PathBuf),
    #[error("Configuration error: {0}")]
    ConfigurationError(String),

    #[error("Manifest corrupted at '{0}': {1}")]
    ManifestCorrupted(PathBuf, String),

    #[error("Conflict with local modifications or unmanaged entries: {0}")]
    Conflict(String),

    #[error("Agent restart required: {0}")]
    RestartRequired(String),

    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
}

/// Installation status of the managed extension or hooks.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ManagedInstallationStatus {
    Absent,
    Current,
    Outdated,
    Modified,
}

impl std::fmt::Display for ManagedInstallationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Absent => write!(f, "absent"),
            Self::Current => write!(f, "current"),
            Self::Outdated => write!(f, "outdated"),
            Self::Modified => write!(f, "modified"),
        }
    }
}

pub type ManagedExtensionStatus = ManagedInstallationStatus;

/// Runtime readiness status for native agent reporting.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ManagedReadinessStatus {
    Ready,
    RestartRequired,
    TrustRequired,
    PolicyDisabled,
    PathMismatch,
    PermissionDenied,
    UnsupportedVersion,
    Unverified,
}

impl std::fmt::Display for ManagedReadinessStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "ready"),
            Self::RestartRequired => write!(f, "restart-required"),
            Self::TrustRequired => write!(f, "trust-required"),
            Self::PolicyDisabled => write!(f, "policy-disabled"),
            Self::PathMismatch => write!(f, "path-mismatch"),
            Self::PermissionDenied => write!(f, "permission-denied"),
            Self::UnsupportedVersion => write!(f, "unsupported-version"),
            Self::Unverified => write!(f, "unverified"),
        }
    }
}

/// Managed hook ownership manifest stored on disk.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ManagedHookManifest {
    pub manifest_version: u32,
    pub agent_kind: AgentKind,
    pub adapter_version: String,
    pub binary_path: String,
    pub launcher_path: String,
    pub launcher_hash: String,
    pub config_path: String,
    pub config_format: String,
    pub owned_hook_events: Vec<String>,
    pub created_directories: Vec<String>,
    pub created_files: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated_ms: Option<u64>,
}

/// Native integration status report for Codex or Claude.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NativeIntegrationStatusReport {
    pub agent_kind: AgentKind,
    pub status: ManagedInstallationStatus,
    pub readiness: ManagedReadinessStatus,
    pub target_path: PathBuf,
    pub launcher_path: PathBuf,
    pub manifest_path: PathBuf,
    pub config_path: Option<PathBuf>,
    pub version: Option<String>,
    pub bundled_version: String,
    pub content_hash: Option<String>,
    pub bundled_hash: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

/// Status report details for an explicit agent directory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExtensionStatusReport {
    pub status: ManagedExtensionStatus,
    pub target_path: PathBuf,
    pub version: Option<String>,
    pub bundled_version: String,
    pub content_hash: Option<String>,
    pub bundled_hash: String,
}

/// Verification result for OMP and Codex path eligibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentPathsVerification {
    pub effective_home: String,
    pub omp_install_dir: String,
    pub omp_notification_dir: String,
    pub omp_status: ManagedExtensionStatus,
    pub omp_can_enable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub omp_reason: Option<String>,
    pub codex_config_dir: String,
    pub codex_notification_dir: String,
    pub codex_config_exists: bool,
    pub codex_can_enable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub codex_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_config_dir: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_notification_dir: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_config_exists: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_can_enable: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub claude_reason: Option<String>,
}

/// Calculate SHA-256 hex digest of string content.
pub fn sha256_hex(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

/// Calculate SHA-256 hex digest of the bundled OMP adapter asset.
pub fn bundled_asset_hash() -> String {
    sha256_hex(OMP_AGENT_STATUS_ASSET)
}

/// Validate that a path is an absolute, non-symlink existing directory.
pub fn validate_safe_dir(dir: &Path) -> Result<(), IntegrationError> {
    if !dir.is_absolute() {
        return Err(IntegrationError::NonAbsolutePath(dir.to_path_buf()));
    }
    let meta = match std::fs::symlink_metadata(dir) {
        Ok(m) => m,
        Err(_) => return Err(IntegrationError::InvalidAgentDirectory(dir.to_path_buf())),
    };
    if meta.file_type().is_symlink() {
        return Err(IntegrationError::SymlinkNotAllowed(dir.to_path_buf()));
    }
    if !meta.is_dir() {
        return Err(IntegrationError::InvalidAgentDirectory(dir.to_path_buf()));
    }
    Ok(())
}

/// Validate that a path is not a symlink and is a regular file if it exists.
/// Returns Ok(true) if exists and is regular file, Ok(false) if absent.
pub fn validate_safe_file(file: &Path) -> Result<bool, IntegrationError> {
    match std::fs::symlink_metadata(file) {
        Ok(meta) => {
            if meta.file_type().is_symlink() {
                Err(IntegrationError::SymlinkNotAllowed(file.to_path_buf()))
            } else if !meta.is_file() {
                Err(IntegrationError::NotRegularFile(file.to_path_buf()))
            } else {
                Ok(true)
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(IntegrationError::Io(e)),
    }
}

/// Maximum allowed configuration file size (1 MiB).
pub const MAX_CONFIG_FILE_BYTES: u64 = 1024 * 1024;

/// Safely read a regular file within bounded size limits, rejecting symlinks.
pub fn read_bounded_safe_file(file: &Path, max_bytes: u64) -> Result<String, IntegrationError> {
    let exists = validate_safe_file(file)?;
    if !exists {
        return Err(IntegrationError::Io(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("File not found: {}", file.display()),
        )));
    }
    let meta = std::fs::symlink_metadata(file)?;
    if meta.len() > max_bytes {
        return Err(IntegrationError::ConfigurationError(format!(
            "Configuration file '{}' exceeds maximum allowed size of {max_bytes} bytes (got {} bytes)",
            file.display(),
            meta.len()
        )));
    }
    let content = std::fs::read_to_string(file)?;
    Ok(content)
}

/// Safely escape a string for single-quoted POSIX shell execution.
pub fn escape_shell_single_quote(s: &str) -> String {
    s.replace('\'', "'\\''")
}

/// Generate the launcher POSIX shell script content.
pub fn render_launcher_script(agent_kind: AgentKind, binary_path: &Path) -> String {
    let kind_str = match agent_kind {
        AgentKind::Codex => "codex",
        AgentKind::Claude => "claude",
        AgentKind::Omp => "omp",
    };
    let bin_path_str = binary_path.to_string_lossy();
    let escaped_bin_path = escape_shell_single_quote(&bin_path_str);

    NATIVE_LAUNCHER_ASSET
        .replace("__AGENT_KIND__", kind_str)
        .replace("__MANAGED_VERSION__", MANAGED_ADAPTER_VERSION)
        .replace("__BINARY_PATH__", &bin_path_str)
        .replace("__ESCAPED_BINARY_PATH__", &escaped_bin_path)
}

/// Parse version and binary path from generated launcher content.
pub fn parse_launcher_metadata(content: &str) -> (Option<String>, Option<String>) {
    let mut version = None;
    let mut binary_path = None;
    for line in content.lines() {
        if let Some(v) = line.strip_prefix("# dam-hopper-managed-version: ") {
            version = Some(v.trim().to_string());
        } else if let Some(b) = line.strip_prefix("# dam-hopper-binary: ") {
            binary_path = Some(b.trim().to_string());
        }
    }
    (version, binary_path)
}

/// Resolve the current executable path, checking that it exists and is executable.
pub fn resolve_stable_binary_path() -> Result<PathBuf, IntegrationError> {
    let current = std::env::current_exe()?;
    let canonical = current.canonicalize().unwrap_or(current);
    if !canonical.is_file() {
        return Err(IntegrationError::ConfigurationError(format!(
            "Current executable not found or not regular file: {}",
            canonical.display()
        )));
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = std::fs::metadata(&canonical) {
            if meta.permissions().mode() & 0o111 == 0 {
                return Err(IntegrationError::ConfigurationError(format!(
                    "Current executable is not executable: {}",
                    canonical.display()
                )));
            }
        }
    }
    Ok(canonical)
}

/// Write a file atomically using a tempfile in the target's parent directory,
/// setting unix permissions if requested.
pub fn atomic_write_file(
    target: &Path,
    content: &[u8],
    mode: Option<u32>,
) -> Result<(), IntegrationError> {
    let parent = target
        .parent()
        .ok_or_else(|| IntegrationError::InvalidAgentDirectory(target.to_path_buf()))?;

    if !parent.exists() {
        std::fs::create_dir_all(parent)?;
    }
    validate_safe_dir(parent)?;

    let mut temp = tempfile::Builder::new()
        .prefix(".dh-tmp-")
        .suffix(".tmp")
        .tempfile_in(parent)?;

    #[cfg(unix)]
    if let Some(m) = mode {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(m);
        temp.as_file().set_permissions(perms)?;
    }

    use std::io::Write;
    temp.write_all(content)?;
    temp.flush()?;
    temp.as_file().sync_all()?;
    temp.persist(target).map_err(|e| e.error)?;
    Ok(())
}

/// Format the complete generated file content including the managed header.
pub fn generate_extension_file_content() -> String {
    let hash = bundled_asset_hash();
    format!(
        "{MANAGED_HEADER_PREFIX}\n{VERSION_PREFIX}{MANAGED_ADAPTER_VERSION}\n{HASH_PREFIX}{hash}\n\n{OMP_AGENT_STATUS_ASSET}"
    )
}

/// Resolve and validate the target extension file path for an agent directory.
pub fn resolve_target_path(agent_dir: &Path) -> Result<PathBuf, IntegrationError> {
    if !agent_dir.is_absolute() {
        return Err(IntegrationError::NonAbsolutePath(agent_dir.to_path_buf()));
    }

    let meta = std::fs::symlink_metadata(agent_dir).map_err(|_| {
        IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf())
    })?;

    if meta.file_type().is_symlink() {
        return Err(IntegrationError::SymlinkNotAllowed(agent_dir.to_path_buf()));
    }
    if !meta.is_dir() {
        return Err(IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf()));
    }

    Ok(agent_dir.join(EXTENSION_SUBPATH))
}

/// Check the status of the managed extension in the specified agent directory.
pub fn check_extension_status(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let target_path = resolve_target_path(agent_dir)?;
    let bundled_hash = bundled_asset_hash();

    let meta = match std::fs::symlink_metadata(&target_path) {
        Ok(m) => m,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Absent,
                target_path,
                version: None,
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: None,
                bundled_hash,
            });
        }
        Err(e) => return Err(IntegrationError::Io(e)),
    };

    if meta.file_type().is_symlink() {
        return Err(IntegrationError::SymlinkNotAllowed(target_path));
    }
    if !meta.file_type().is_file() {
        return Err(IntegrationError::NotRegularFile(target_path));
    }

    let existing_content = std::fs::read_to_string(&target_path)?;
    let expected_content = generate_extension_file_content();

    let normalized_existing = existing_content.replace("\r\n", "\n");
    let normalized_expected = expected_content.replace("\r\n", "\n");

    // Fast path: exact match with bundled generated file
    if normalized_existing == normalized_expected {
        return Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Current,
            target_path,
            version: Some(MANAGED_ADAPTER_VERSION.to_string()),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(bundled_hash.clone()),
            bundled_hash,
        });
    }

    // Split header and body cleanly across LF and CRLF
    let (header_part, actual_body) = if let Some((head, body)) = normalized_existing.split_once("\n\n") {
        (head, body)
    } else {
        (normalized_existing.as_str(), "")
    };

    let mut recorded_version: Option<String> = None;
    let mut recorded_hash: Option<String> = None;

    for line in header_part.lines() {
        if let Some(v) = line.strip_prefix(VERSION_PREFIX) {
            recorded_version = Some(v.trim().to_string());
        } else if let Some(h) = line.strip_prefix(HASH_PREFIX) {
            recorded_hash = Some(h.trim().to_string());
        }
    }

    let (Some(ver), Some(hash)) = (recorded_version, recorded_hash) else {
        // Missing managed header markers => unmanaged/modified
        return Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Modified,
            target_path,
            version: None,
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: None,
            bundled_hash,
        });
    };
    let actual_body_hash = sha256_hex(actual_body);

    if actual_body_hash != hash {
        // Hash mismatch between header and actual body => locally modified
        Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Modified,
            target_path,
            version: Some(ver),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(actual_body_hash),
            bundled_hash,
        })
    } else {
        // Body matches recorded hash cleanly, but hash != bundled_hash => outdated version
        Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Outdated,
            target_path,
            version: Some(ver),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(hash),
            bundled_hash,
        })
    }
}

/// Atomically install or upgrade the managed OMP extension in the specified agent directory.
pub fn install_extension(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let report = check_extension_status(agent_dir)?;
    match report.status {
        ManagedExtensionStatus::Current => {
            // Already current and valid
            Ok(report)
        }
        ManagedExtensionStatus::Modified => {
            Err(IntegrationError::RefusingOverwriteModified(report.target_path))
        }
        ManagedExtensionStatus::Absent | ManagedExtensionStatus::Outdated => {
            let target_path = &report.target_path;
            let extensions_dir = target_path
                .parent()
                .ok_or_else(|| IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf()))?;

            if !extensions_dir.exists() {
                std::fs::create_dir_all(extensions_dir)?;
            } else {
                let ext_meta = std::fs::symlink_metadata(extensions_dir)?;
                if ext_meta.file_type().is_symlink() {
                    return Err(IntegrationError::SymlinkNotAllowed(extensions_dir.to_path_buf()));
                }
                if !ext_meta.is_dir() {
                    return Err(IntegrationError::InvalidAgentDirectory(extensions_dir.to_path_buf()));
                }
            }

            let file_content = generate_extension_file_content();

            // Atomic write: write to tempfile in the same directory, then persist/rename
            use std::io::Write;
            let mut temp = tempfile::Builder::new()
                .prefix(".dam-hopper-omp-")
                .suffix(".tmp")
                .tempfile_in(extensions_dir)?;

            temp.write_all(file_content.as_bytes())?;
            temp.flush()?;
            temp.as_file().sync_all()?;
            temp.persist(target_path).map_err(|e| e.error)?;

            Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Current,
                target_path: target_path.clone(),
                version: Some(MANAGED_ADAPTER_VERSION.to_string()),
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: Some(report.bundled_hash.clone()),
                bundled_hash: report.bundled_hash,
            })
        }
    }
}

/// Uninstall the managed OMP extension if present and uncorrupted.
pub fn uninstall_extension(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let report = check_extension_status(agent_dir)?;
    match report.status {
        ManagedExtensionStatus::Absent => {
            // Already absent
            Ok(report)
        }
        ManagedExtensionStatus::Modified => {
            Err(IntegrationError::RefusingDeleteModified(report.target_path))
        }
        ManagedExtensionStatus::Current | ManagedExtensionStatus::Outdated => {
            std::fs::remove_file(&report.target_path)?;
            Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Absent,
                target_path: report.target_path,
                version: None,
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: None,
                bundled_hash: report.bundled_hash,
            })
        }
    }
}

/// Dispatch status check for native agent integrations (Codex, Claude).
pub fn check_native_integration_status(
    agent_kind: AgentKind,
    agent_dir: &Path,
) -> Result<NativeIntegrationStatusReport, IntegrationError> {
    match agent_kind {
        AgentKind::Codex => crate::agent_status::codex_integration::check_codex_status(agent_dir),
        AgentKind::Claude => crate::agent_status::claude_integration::check_claude_status(agent_dir),
        AgentKind::Omp => Err(IntegrationError::ConfigurationError(
            "OMP uses extension lifecycle rather than native hooks".to_string(),
        )),
    }
}

/// Dispatch installation for native agent integrations (Codex, Claude).
pub fn install_native_integration(
    agent_kind: AgentKind,
    agent_dir: &Path,
) -> Result<NativeIntegrationStatusReport, IntegrationError> {
    match agent_kind {
        AgentKind::Codex => crate::agent_status::codex_integration::install_codex(agent_dir),
        AgentKind::Claude => crate::agent_status::claude_integration::install_claude(agent_dir),
        AgentKind::Omp => Err(IntegrationError::ConfigurationError(
            "OMP uses extension lifecycle rather than native hooks".to_string(),
        )),
    }
}

/// Dispatch uninstallation for native agent integrations (Codex, Claude).
pub fn uninstall_native_integration(
    agent_kind: AgentKind,
    agent_dir: &Path,
) -> Result<NativeIntegrationStatusReport, IntegrationError> {
    match agent_kind {
        AgentKind::Codex => crate::agent_status::codex_integration::uninstall_codex(agent_dir),
        AgentKind::Claude => crate::agent_status::claude_integration::uninstall_claude(agent_dir),
        AgentKind::Omp => Err(IntegrationError::ConfigurationError(
            "OMP uses extension lifecycle rather than native hooks".to_string(),
        )),
    }
}
