use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;

/// Bundled standalone OMP TypeScript extension source.
pub const OMP_AGENT_STATUS_ASSET: &str = include_str!("assets/omp-agent-status.ts");

/// Current managed adapter version.
pub const MANAGED_ADAPTER_VERSION: &str = "1.0.0";

/// Relative subpath within the OMP agent directory.
pub const EXTENSION_SUBPATH: &str = "extensions/dam-hopper-agent-status.ts";

const MANAGED_HEADER_PREFIX: &str = "// @generated by dam-hopper-server integration omp";
const VERSION_PREFIX: &str = "// dam-hopper-managed-version: ";
const HASH_PREFIX: &str = "// dam-hopper-content-sha256: ";

#[derive(Debug, Error)]
pub enum IntegrationError {
    #[error("Agent directory must be an absolute path: '{0}'")]
    NonAbsolutePath(PathBuf),

    #[error("Agent directory does not exist or is not a directory: '{0}'")]
    InvalidAgentDirectory(PathBuf),

    #[error("Refusing to operate on symlink: '{0}'")]
    SymlinkNotAllowed(PathBuf),

    #[error("Target path is not a regular file: '{0}'")]
    NotRegularFile(PathBuf),

    #[error("Refusing to overwrite locally modified or unmanaged file at '{0}'")]
    RefusingOverwriteModified(PathBuf),

    #[error("Refusing to delete locally modified or unmanaged file at '{0}'")]
    RefusingDeleteModified(PathBuf),

    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
}

/// Installation status of the managed OMP extension.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ManagedExtensionStatus {
    Absent,
    Current,
    Outdated,
    Modified,
}

impl std::fmt::Display for ManagedExtensionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Absent => write!(f, "absent"),
            Self::Current => write!(f, "current"),
            Self::Outdated => write!(f, "outdated"),
            Self::Modified => write!(f, "modified"),
        }
    }
}

/// Status report details for an explicit agent directory.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExtensionStatusReport {
    pub status: ManagedExtensionStatus,
    pub target_path: PathBuf,
    pub version: Option<String>,
    pub bundled_version: String,
    pub content_hash: Option<String>,
    pub bundled_hash: String,
}

/// Verification result for OMP and Codex path eligibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentPathsVerification {
    pub effective_home: String,
    pub omp_install_dir: String,
    pub omp_notification_dir: String,
    pub omp_status: ManagedExtensionStatus,
    pub omp_can_enable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub omp_reason: Option<String>,
    pub codex_config_dir: String,
    pub codex_notification_dir: String,
    pub codex_config_exists: bool,
    pub codex_can_enable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub codex_reason: Option<String>,
}

/// Calculate SHA-256 hex digest of string content.
pub fn sha256_hex(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    hex::encode(hasher.finalize())
}

/// Calculate SHA-256 hex digest of the bundled OMP adapter asset.
pub fn bundled_asset_hash() -> String {
    sha256_hex(OMP_AGENT_STATUS_ASSET)
}

/// Format the complete generated file content including the managed header.
pub fn generate_extension_file_content() -> String {
    let hash = bundled_asset_hash();
    format!(
        "{MANAGED_HEADER_PREFIX}\n{VERSION_PREFIX}{MANAGED_ADAPTER_VERSION}\n{HASH_PREFIX}{hash}\n\n{OMP_AGENT_STATUS_ASSET}"
    )
}

/// Resolve and validate the target extension file path for an agent directory.
pub fn resolve_target_path(agent_dir: &Path) -> Result<PathBuf, IntegrationError> {
    if !agent_dir.is_absolute() {
        return Err(IntegrationError::NonAbsolutePath(agent_dir.to_path_buf()));
    }

    let meta = std::fs::symlink_metadata(agent_dir).map_err(|_| {
        IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf())
    })?;

    if meta.file_type().is_symlink() {
        return Err(IntegrationError::SymlinkNotAllowed(agent_dir.to_path_buf()));
    }
    if !meta.is_dir() {
        return Err(IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf()));
    }

    Ok(agent_dir.join(EXTENSION_SUBPATH))
}

/// Check the status of the managed extension in the specified agent directory.
pub fn check_extension_status(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let target_path = resolve_target_path(agent_dir)?;
    let bundled_hash = bundled_asset_hash();

    let meta = match std::fs::symlink_metadata(&target_path) {
        Ok(m) => m,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Absent,
                target_path,
                version: None,
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: None,
                bundled_hash,
            });
        }
        Err(e) => return Err(IntegrationError::Io(e)),
    };

    if meta.file_type().is_symlink() {
        return Err(IntegrationError::SymlinkNotAllowed(target_path));
    }
    if !meta.file_type().is_file() {
        return Err(IntegrationError::NotRegularFile(target_path));
    }

    let existing_content = std::fs::read_to_string(&target_path)?;
    let expected_content = generate_extension_file_content();

    let normalized_existing = existing_content.replace("\r\n", "\n");
    let normalized_expected = expected_content.replace("\r\n", "\n");

    // Fast path: exact match with bundled generated file
    if normalized_existing == normalized_expected {
        return Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Current,
            target_path,
            version: Some(MANAGED_ADAPTER_VERSION.to_string()),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(bundled_hash.clone()),
            bundled_hash,
        });
    }

    // Split header and body cleanly across LF and CRLF
    let (header_part, actual_body) = if let Some((head, body)) = normalized_existing.split_once("\n\n") {
        (head, body)
    } else {
        (normalized_existing.as_str(), "")
    };

    let mut recorded_version: Option<String> = None;
    let mut recorded_hash: Option<String> = None;

    for line in header_part.lines() {
        if let Some(v) = line.strip_prefix(VERSION_PREFIX) {
            recorded_version = Some(v.trim().to_string());
        } else if let Some(h) = line.strip_prefix(HASH_PREFIX) {
            recorded_hash = Some(h.trim().to_string());
        }
    }

    let (Some(ver), Some(hash)) = (recorded_version, recorded_hash) else {
        // Missing managed header markers => unmanaged/modified
        return Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Modified,
            target_path,
            version: None,
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: None,
            bundled_hash,
        });
    };
    let actual_body_hash = sha256_hex(actual_body);

    if actual_body_hash != hash {
        // Hash mismatch between header and actual body => locally modified
        Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Modified,
            target_path,
            version: Some(ver),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(actual_body_hash),
            bundled_hash,
        })
    } else {
        // Body matches recorded hash cleanly, but hash != bundled_hash => outdated version
        Ok(ExtensionStatusReport {
            status: ManagedExtensionStatus::Outdated,
            target_path,
            version: Some(ver),
            bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
            content_hash: Some(hash),
            bundled_hash,
        })
    }
}

/// Atomically install or upgrade the managed OMP extension in the specified agent directory.
pub fn install_extension(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let report = check_extension_status(agent_dir)?;
    match report.status {
        ManagedExtensionStatus::Current => {
            // Already current and valid
            Ok(report)
        }
        ManagedExtensionStatus::Modified => {
            Err(IntegrationError::RefusingOverwriteModified(report.target_path))
        }
        ManagedExtensionStatus::Absent | ManagedExtensionStatus::Outdated => {
            let target_path = &report.target_path;
            let extensions_dir = target_path
                .parent()
                .ok_or_else(|| IntegrationError::InvalidAgentDirectory(agent_dir.to_path_buf()))?;

            if !extensions_dir.exists() {
                std::fs::create_dir_all(extensions_dir)?;
            } else {
                let ext_meta = std::fs::symlink_metadata(extensions_dir)?;
                if ext_meta.file_type().is_symlink() {
                    return Err(IntegrationError::SymlinkNotAllowed(extensions_dir.to_path_buf()));
                }
                if !ext_meta.is_dir() {
                    return Err(IntegrationError::InvalidAgentDirectory(extensions_dir.to_path_buf()));
                }
            }

            let file_content = generate_extension_file_content();

            // Atomic write: write to tempfile in the same directory, then persist/rename
            use std::io::Write;
            let mut temp = tempfile::Builder::new()
                .prefix(".dam-hopper-omp-")
                .suffix(".tmp")
                .tempfile_in(extensions_dir)?;

            temp.write_all(file_content.as_bytes())?;
            temp.flush()?;
            temp.as_file().sync_all()?;
            temp.persist(target_path).map_err(|e| e.error)?;

            Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Current,
                target_path: target_path.clone(),
                version: Some(MANAGED_ADAPTER_VERSION.to_string()),
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: Some(report.bundled_hash.clone()),
                bundled_hash: report.bundled_hash,
            })
        }
    }
}

/// Uninstall the managed OMP extension if present and uncorrupted.
pub fn uninstall_extension(agent_dir: &Path) -> Result<ExtensionStatusReport, IntegrationError> {
    let report = check_extension_status(agent_dir)?;
    match report.status {
        ManagedExtensionStatus::Absent => {
            // Already absent
            Ok(report)
        }
        ManagedExtensionStatus::Modified => {
            Err(IntegrationError::RefusingDeleteModified(report.target_path))
        }
        ManagedExtensionStatus::Current | ManagedExtensionStatus::Outdated => {
            std::fs::remove_file(&report.target_path)?;
            Ok(ExtensionStatusReport {
                status: ManagedExtensionStatus::Absent,
                target_path: report.target_path,
                version: None,
                bundled_version: MANAGED_ADAPTER_VERSION.to_string(),
                content_hash: None,
                bundled_hash: report.bundled_hash,
            })
        }
    }
}
