#!/bin/sh
# @generated by dam-hopper-server integration __AGENT_KIND__
# dam-hopper-managed-version: __MANAGED_VERSION__
# dam-hopper-binary: __BINARY_PATH__
exec '__ESCAPED_BINARY_PATH__' integration __AGENT_KIND__ report-hook
